//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblComment
    {
        public int CommentId { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string CommentContent { get; set; }
        public Nullable<int> BlogId { get; set; }
    
        public virtual TblBlog TblBlog { get; set; }
    }
}
